# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to folder for Windows, Linux and MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish win-x64
      run: |
        dotnet publish -p:PublishProfile=Folder_win-x64        
    - name: Publish linux-x64
      run: |
        dotnet publish -p:PublishProfile=Folder_linux-x64        
    - name: Publish osx-x64
      run: |
        dotnet publish -p:PublishProfile=Folder_osx-x64
    - name: Upload win-x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Distributable for win-x64
        path: ${{ github.workspace }}/src/Zengenti.Contensis.RequestHandler.LocalDevelopment/bin/Debug/net6.0/win-x64/publish/
    - name: Upload linux-x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Distributable for linux-x64
        path: ${{ github.workspace }}/src/Zengenti.Contensis.RequestHandler.LocalDevelopment/bin/Debug/net6.0/linux-x64/publish/        
    - name: Upload osx-x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Distributable for osx-x64
        path: ${{ github.workspace }}/src/Zengenti.Contensis.RequestHandler.LocalDevelopment/bin/Debug/net6.0/osx-x64/publish/
            
